// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rout_guide.proto

package spring.boot.learn.grpc.demo.routguide;

public interface FeatureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:spring.boot.learn.grpc.demo.Feature)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.spring.boot.learn.grpc.demo.Point location = 2;</code>
   */
  boolean hasLocation();
  /**
   * <code>.spring.boot.learn.grpc.demo.Point location = 2;</code>
   */
  spring.boot.learn.grpc.demo.routguide.Point getLocation();
  /**
   * <code>.spring.boot.learn.grpc.demo.Point location = 2;</code>
   */
  spring.boot.learn.grpc.demo.routguide.PointOrBuilder getLocationOrBuilder();
}
