// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rout_guide.proto

package spring.boot.learn.grpc.demo.routguide;

public interface PointOrBuilder extends
    // @@protoc_insertion_point(interface_extends:spring.boot.learn.grpc.demo.Point)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 latitude = 1;</code>
   */
  int getLatitude();

  /**
   * <code>int32 longitude = 2;</code>
   */
  int getLongitude();
}
