// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rout_guide.proto

package spring.boot.learn.grpc.demo.routguide;

public interface RectangleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:spring.boot.learn.grpc.demo.Rectangle)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.spring.boot.learn.grpc.demo.Point lo = 1;</code>
   */
  boolean hasLo();
  /**
   * <code>.spring.boot.learn.grpc.demo.Point lo = 1;</code>
   */
  Point getLo();
  /**
   * <code>.spring.boot.learn.grpc.demo.Point lo = 1;</code>
   */
  PointOrBuilder getLoOrBuilder();

  /**
   * <code>.spring.boot.learn.grpc.demo.Point hi = 2;</code>
   */
  boolean hasHi();
  /**
   * <code>.spring.boot.learn.grpc.demo.Point hi = 2;</code>
   */
  Point getHi();
  /**
   * <code>.spring.boot.learn.grpc.demo.Point hi = 2;</code>
   */
  PointOrBuilder getHiOrBuilder();
}
