// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rout_guide.proto

package spring.boot.learn.grpc.demo.routguide;

public interface RouteNoteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:spring.boot.learn.grpc.demo.RouteNote)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.spring.boot.learn.grpc.demo.Point location = 1;</code>
   */
  boolean hasLocation();
  /**
   * <code>.spring.boot.learn.grpc.demo.Point location = 1;</code>
   */
  Point getLocation();
  /**
   * <code>.spring.boot.learn.grpc.demo.Point location = 1;</code>
   */
  PointOrBuilder getLocationOrBuilder();

  /**
   * <code>string message = 2;</code>
   */
  String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
